### ISSUE TITLE
`Open in SAM Detector` feature broken after commit 27c5368

### ISSUE THREAD

**Issue by datismik** [ltdrdata/ComfyUI-Impact-Pack#1041]
The `Open in SAM Detector` feature has stopped working since commit 27c5368.
After clicking the `Detect` button, the following error appears in the console:

```
Traceback (most recent call last):
  File "home/user/ComfyUI/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
  File "home/user/ComfyUI/venv/lib/python3.10/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
  File "home/user/ComfyUI/venv/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "home/user/ComfyUI/server.py", line 52, in cache_control
    response: web.Response = await handler(request)
  File "home/user/ComfyUI/server.py", line 78, in cors_middleware
    response = await handler(request)
  File "home/user/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 148, in sam_detect
    mask = core.combine_masks2(detected_masks)
AttributeError: module 'impact.core' has no attribute 'combine_masks2'
```

**Comment by dart84** [comment]
Indeed, same here.

> [Impact Pack] Loading SAM model 'C:\Program Files\ComfyUI_windows_portable\ComfyUI\models\sams\sam_vit_b_01ec64.pth'
> [Impact Pack] SAM model loaded.
> Error handling request from 127.0.0.1
> Traceback (most recent call last):
>   File "C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 510, in _handle_request
>     resp = await request_handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 569, in _handle
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
>     return await handler(request)
>            ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ComfyUI_windows_portable\ComfyUI\server.py", line 52, in cache_control
>     response: web.Response = await handler(request)
>                              ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ComfyUI_windows_portable\ComfyUI\server.py", line 144, in origin_only_middleware
>     response = await handler(request)
>                ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 148, in sam_detect
>     mask = core.combine_masks2(detected_masks)
>            ^^^^^^^^^^^^^^^^^^^
> AttributeError: module 'impact.core' has no attribute 'combine_masks2'

**Comment by Gxinz** [comment]
Same here

Traceback (most recent call last):
  File "C:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\server.py", line 52, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\server.py", line 144, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_server.py", line 148, in sam_detect
    mask = core.combine_masks2(detected_masks)
           ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'impact.core' has no attribute 'combine_masks2'
