### ISSUE TITLE
Error occurred when executing FaceDetailer:

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#244]
after update today, FaceDetailer no work

Error occurred when executing FaceDetailer:

UltraBBoxDetector.detect() got an unexpected keyword argument 'detailer_hook'

File "F:\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)

**Comment by xueqing0622** [comment]
The detailer is ok!

**Comment by xueqing0622** [comment]
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Updating subpack
[ComfyUI-Impact-Pack]: Dependency installation has failed. Please install manually.
[WinError 5] 拒绝访问。: 'F:\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack\\.git\\objects\\pack\\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
### Loading: ComfyUI-Inspire-Pack (V0.32.2)
### Loading: ComfyUI-Manager (V0.36)
### ComfyUI Revision: 1617 [d1d2fea8] | Released on '2023-10-25'

**Comment by suede299** [comment]
Same issues, Problems only appear after **Subpack** update
----------------------------------------------------------------------------
Error occurred when executing FaceDetailer:

MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'

File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)

**Comment by xueqing0622** [comment]
remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
because this error
[WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'

**Comment by suede299** [comment]
> remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall. because this error [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'

我也无法用git pull更新subpack，都是去下载那两个文件手动覆盖的。

**Comment by xueqing0622** [comment]
> > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall. because this error [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> 
> 我也无法用git pull更新subpack，都是去下载那两个文件手动覆盖的。

麻烦点, 但能解决就好,只是这个错误出现两次了,希望git主把这个bug修了,

**Comment by ltdrdata** [comment]
> remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> because this error
> [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'

You should turn off ComfyUI before remove it.
Windows' file locking system is so annoying.

**Comment by suede299** [comment]
> > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> > because this error
> > [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> 
> You should turn off ComfyUI before remove it. Windows' file locking system is so annoying.
I updated all the relevant nodes and still get the following error:

Error occurred when executing FaceDetailer:

MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'

File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)

**Comment by xueqing0622** [comment]
> > > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> > > because this error
> > > [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> > 
> > 
> > You should turn off ComfyUI before remove it. Windows' file locking system is so annoying.
> > I updated all the relevant nodes and still get the following error:
> 
> Error occurred when executing FaceDetailer:
> 
> MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'
> 
> File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)

你在custom node里面删除,重新git clone一下
然后再运行下面这个命令,把subpack也自己手动更新一下
git clone -v -- https://githubfast.com/ltdrdata/ComfyUI-Impact-Subpack F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack
中国建议用githubfast, 目录你自己根据需要改变

You delete the custom node, re-git clone it, and then run this command to update the subpack manually 
git clone -v -- https://githubfast.com/ltdrdata/ComfyUI-Impact-Subpack F:\ ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack 
in China suggests to use githubfast, you can change the directory according to your needs.

**Comment by ltdrdata** [comment]
> > > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> > > because this error
> > > [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> > 
> > 
> > You should turn off ComfyUI before remove it. Windows' file locking system is so annoying.
> > I updated all the relevant nodes and still get the following error:
> 
> Error occurred when executing FaceDetailer:
> 
> MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'
> 
> File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)

Update `Inspire Pack` to latest version.

**Comment by suede299** [comment]
> > > > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> > > > because this error
> > > > [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> > > 
> > > 
> > > You should turn off ComfyUI before remove it. Windows' file locking system is so annoying.
> > > I updated all the relevant nodes and still get the following error:
> > 
> > 
> > Error occurred when executing FaceDetailer:
> > MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'
> > File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
> 
> Update `Inspire Pack` to latest version.

I think I updated everything, but I'm still getting the same error as above.
I even created new nodes.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/85022330/643d3a7f-1d7a-401c-8072-13e4bcb73416)
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/85022330/9a618612-f2bd-446a-89e5-601041a88d11)

**Comment by ltdrdata** [comment]
> MediaPipeFaceMeshDetector

oops... I modified wrong directorie's file. The patch didn't commited. Update `Inspire Pack` again.
V0.32.4

**Comment by suede299** [comment]
> > MediaPipeFaceMeshDetector
> 
> oops... I modified wrong directorie's file. The patch didn't commited. Update `Inspire Pack` again. V0.32.4

Did you commit? I don't see any updates yet.

**Comment by ltdrdata** [comment]
> > > MediaPipeFaceMeshDetector
> > 
> > oops... I modified wrong directorie's file. The patch didn't commited. Update `Inspire Pack` again. V0.32.4
> 
> Did you commit? I don't see any updates yet.

OMG. I didn't pushed after commit.
I am away from home. I'll push it when I get back to home.

**Comment by ltdrdata** [comment]
> > > MediaPipeFaceMeshDetector
> > 
> > 
> > oops... I modified wrong directorie's file. The patch didn't commited. Update `Inspire Pack` again. V0.32.4
> 
> Did you commit? I don't see any updates yet.

Just pushed. Try it.

**Comment by suede299** [comment]
> > > > MediaPipeFaceMeshDetector
> > > 
> > > 
> > > oops... I modified wrong directorie's file. The patch didn't commited. Update `Inspire Pack` again. V0.32.4
> > 
> > 
> > Did you commit? I don't see any updates yet.
> 
> Just pushed. Try it.

It's back to normal after the update

**Comment by gdtiti** [comment]
Loads checkpoint by local backend from path: /home/titi/work/_Pic/ComfyUI/models/mmdets/bbox/mmdet_anime-face_yolov3.pth
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/titi/work/_Pic/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/titi/work/_Pic/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/titi/work/_Pic/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/titi/work/_Pic/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 424, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "/home/titi/work/_Pic/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 376, in enhance_face
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
TypeError: BBoxDetector.detect() got an unexpected keyword argument 'detailer_hook'

**Comment by gdtiti** [comment]
### Loading: ComfyUI-Impact-Pack (V4.28.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
### Loading: ComfyUI-Workflow-Component (V0.43.3) !! WARN: This is an experimental extension. Extremely unstable. !!
### Loading: ComfyUI-Inspire-Pack (V0.33)

**Comment by ltdrdata** [comment]
> ### Loading: ComfyUI-Impact-Pack (V4.28.2)
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.3)
> ### Loading: ComfyUI-Workflow-Component (V0.43.3) !! WARN: This is an experimental extension. Extremely unstable. !!
> ### Loading: ComfyUI-Inspire-Pack (V0.33)

Just fixed. It will work on V4.28.3

**Comment by DENG-XC** [comment]
> > > > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> > > > because this error
> > > > [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> > > 
> > > 
> > > You should turn off ComfyUI before remove it. Windows' file locking system is so annoying.
> > > I updated all the relevant nodes and still get the following error:
> > 
> > 
> > Error occurred when executing FaceDetailer:
> > MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'
> > File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
> 
> 你在custom node里面删除,重新git clone一下 然后再运行下面这个命令,把subpack也自己手动更新一下 git clone -v -- https://githubfast.com/ltdrdata/ComfyUI-Impact-Subpack F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack 中国建议用githubfast, 目录你自己根据需要改变
> 
> You delete the custom node, re-git clone it, and then run this command to update the subpack manually git clone -v -- https://githubfast.com/ltdrdata/ComfyUI-Impact-Subpack F:\ ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack in China suggests to use githubfast, you can change the directory according to your needs.

你好，我运行facedetailer这个节点时会触发和你一样的错误，请问该如何重新安装这个插件？谢谢

Hi, I have same problem as you when execute facedetail. I am new to comfyui, can you explain how to reinstall this addon? thanks.

**Comment by ltdrdata** [comment]
> > > > > remove and reinstall by manually will fixed the error, This is the second time I've had to delete and reinstall.
> > > > > because this error
> > > > > [WinError 5] Denial of access。: 'F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack.git\objects\pack\pack-fb2a7d253ad273e79e8235df196a16503ae5c6e3.idx'
> > > > 
> > > > 
> > > > You should turn off ComfyUI before remove it. Windows' file locking system is so annoying.
> > > > I updated all the relevant nodes and still get the following error:
> > > 
> > > 
> > > Error occurred when executing FaceDetailer:
> > > MediaPipeFaceMeshDetector.detect() got an unexpected keyword argument 'detailer_hook'
> > > File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 424, in doit enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "D:\StableSwarmUI\dlbackend\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 376, in enhance_face segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
> > 
> > 
> > 你在custom node里面删除,重新git clone一下 然后再运行下面这个命令,把subpack也自己手动更新一下 git clone -v -- https://githubfast.com/ltdrdata/ComfyUI-Impact-Subpack F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack 中国建议用githubfast, 目录你自己根据需要改变
> > You delete the custom node, re-git clone it, and then run this command to update the subpack manually git clone -v -- https://githubfast.com/ltdrdata/ComfyUI-Impact-Subpack F:\ ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack in China suggests to use githubfast, you can change the directory according to your needs.
> 
> 你好，我运行facedetailer这个节点时会触发和你一样的错误，请问该如何重新安装这个插件？谢谢
> 
> Hi, I have same problem as you when execute facedetail. I am new to comfyui, can you explain how to reinstall this addon? thanks.

Just do 'update all' on ComfyUI-Manager.
