### ISSUE TITLE
AttributeError: 'GITSScheduler' object has no attribute 'get_sigmas'

### ISSUE THREAD

**Issue by Neytiri7** [ltdrdata/ComfyUI-Impact-Pack#1129]
```
!!! Exception during processing !!! 'GITSScheduler' object has no attribute 'get_sigmas'
Traceback (most recent call last):
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\execution.py", line 496, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\execution.py", line 315, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\execution.py", line 289, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\execution.py", line 277, in process_inputs
    result = f(**inputs)
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 1906, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              sampler_name, scheduler, positive, negative, denoise, feather, noise_mask,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                              cycle=cycle, inpaint_model=inpaint_model, noise_mask_feather=noise_mask_feather,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              scheduler_func_opt=scheduler_func_opt, tiled_encode=tiled_encode, tiled_decode=tiled_decode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 362, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    seg.bbox, seg_seed, steps, cfg, sampler_name, scheduler,
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
                                                    scheduler_func=scheduler_func_opt, vae_tiled_encode=tiled_encode,
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    vae_tiled_decode=tiled_decode)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\core.py", line 383, in enhance_detail
    refined_latent = impact_sampling.ksampler_wrapper(model2, seed2, steps2, cfg2, sampler_name2, scheduler2, positive2, negative2,
                                                      refined_latent, denoise2, refiner_ratio, refiner_model, refiner_clip, refiner_positive, refiner_negative,
                                                      noise=noise, scheduler_func=scheduler_func, sampler_opt=sampler_opt)
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 209, in ksampler_wrapper
    refined_latent = separated_sample(model, True, seed, advanced_steps, cfg, sampler_name, scheduler,
                                      positive, negative, latent_image, start_at_step, end_at_step, False,
                                      sigma_ratio=sigma_factor, sampler_opt=sampler_opt, noise=noise, scheduler_func=scheduler_func)
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 151, in separated_sample
    total_sigmas = scheduler_func(model, sampler_name, steps)
  File "W:\SynologyDrive\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\special_samplers.py", line 667, in f
    return scheduler.get_sigmas(coeff, steps, denoise)[0]
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GITSScheduler' object has no attribute 'get_sigmas'
```

**Comment by Carrott2016** [comment]
Same error here after updating ComfyUI to V0.3.66

0: 384x640 1 face, 32.9ms
Speed: 96.4ms preprocess, 32.9ms inference, 664.5ms postprocess per image at shape (1, 3, 384, 640)
Detailer: segment upscale for ((np.float32(162.3794), np.float32(209.65576))) | crop region (405, 524) x 1.9544697999954224 -> (791, 1024)
Requested to load AutoencodingEngine
loaded completely 19339.650466918945 159.87335777282715 True
[Impact Pack] vae encoded in 0.6s
!!! Exception during processing !!! 'GITSScheduler' object has no attribute 'get_sigmas'
Traceback (most recent call last):
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\execution.py", line 498, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\execution.py", line 316, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\execution.py", line 290, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\execution.py", line 278, in process_inputs
    result = f(**inputs)
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~^
        single_image.unsqueeze(0), model, clip, vae, guide_size, guide_size_for, max_size, seed + i, steps, cfg, sampler_name, scheduler,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
        cycle=cycle, inpaint_model=inpaint_model, noise_mask_feather=noise_mask_feather, scheduler_func_opt=scheduler_func_opt,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        tiled_encode=tiled_encode, tiled_decode=tiled_decode)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 830, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              sampler_name, scheduler, positive, negative, denoise, feather, noise_mask,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                              cycle=cycle, inpaint_model=inpaint_model, noise_mask_feather=noise_mask_feather,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                              scheduler_func_opt=scheduler_func_opt, tiled_encode=tiled_encode, tiled_decode=tiled_decode)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 362, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
                                ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    seg.bbox, seg_seed, steps, cfg, sampler_name, scheduler,
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
                                                    scheduler_func=scheduler_func_opt, vae_tiled_encode=tiled_encode,
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                    vae_tiled_decode=tiled_decode)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\core.py", line 383, in enhance_detail
    refined_latent = impact_sampling.ksampler_wrapper(model2, seed2, steps2, cfg2, sampler_name2, scheduler2, positive2, negative2,
                                                      refined_latent, denoise2, refiner_ratio, refiner_model, refiner_clip, refiner_positive, refiner_negative,
                                                      noise=noise, scheduler_func=scheduler_func, sampler_opt=sampler_opt)
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 209, in ksampler_wrapper
    refined_latent = separated_sample(model, True, seed, advanced_steps, cfg, sampler_name, scheduler,
                                      positive, negative, latent_image, start_at_step, end_at_step, False,
                                      sigma_ratio=sigma_factor, sampler_opt=sampler_opt, noise=noise, scheduler_func=scheduler_func)
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 151, in separated_sample
    total_sigmas = scheduler_func(model, sampler_name, steps)
  File "D:\Ups\StableDiffusion\ComfyUI_portable_0357\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\special_samplers.py", line 667, in f
    return scheduler.get_sigmas(coeff, steps, denoise)[0]
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GITSScheduler' object has no attribute 'get_sigmas'

**Comment by feidexiang** [comment]
same error

**Comment by tonkeyhonk** [comment]
In this file ..\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\special_samplers.py
change line 667 to:
return scheduler.execute(coeff, steps, denoise)[0]

**Comment by Carrott2016** [comment]
> In this file ..\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\special_samplers.py change line 667 to: return scheduler.execute(coeff, steps, denoise)[0]

Thank you very much, that worked. If this is such a small fix, I wonder why the master Dr.Lt.Data did not address this issue yet.

**Comment by ltdrdata** [comment]
This is caused by the compatibility patches for the v3 node updates in ComfyUI’s core nodes. Please update to the latest version of ComfyUI.

**Comment by JaneDoe84** [comment]
> This is caused by the compatibility patches for the v3 node updates in ComfyUI’s core nodes. Please update to the latest version of ComfyUI.

I have same Problem and did what you wrote, but still same Problem.
**ComfyUI version:** 0.3.70
**ComfyUI frontend version:** 1.28.8
**ComfyUI-Impact-Pack:** 8.28.0

**CLI Error:**
0: 384x640 1 face, 6.5ms
Speed: 0.0ms preprocess, 6.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
Detailer: segment upscale for ((np.float32(161.90735), np.float32(261.93805))) | crop region (485, 768) x 1.3336893320083618 -> (646, 1024)
[Impact Pack] vae encoded in 0.2s
!!! Exception during processing !!! 'GITSScheduler' object has no attribute 'get_sigmas'
Traceback (most recent call last):
  File "H:\Comfyui\ComfyUI\execution.py", line 510, in execute
    output_data, output_ui, has_subgraph, has_pending_tasks = await get_output_data(prompt_id, unique_id, obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\execution.py", line 324, in get_output_data
    return_values = await _async_map_node_over_list(prompt_id, unique_id, obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb, hidden_inputs=hidden_inputs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\execution.py", line 298, in _async_map_node_over_list
    await process_inputs(input_dict, i)
  File "H:\Comfyui\ComfyUI\execution.py", line 286, in process_inputs
    result = f(**inputs)
             ^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 876, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 830, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_pack.py", line 362, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\core.py", line 383, in enhance_detail
    refined_latent = impact_sampling.ksampler_wrapper(model2, seed2, steps2, cfg2, sampler_name2, scheduler2, positive2, negative2,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 209, in ksampler_wrapper
    refined_latent = separated_sample(model, True, seed, advanced_steps, cfg, sampler_name, scheduler,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\impact_sampling.py", line 151, in separated_sample
    total_sigmas = scheduler_func(model, sampler_name, steps)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Comfyui\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\special_samplers.py", line 667, in f
    return scheduler.get_sigmas(coeff, steps, denoise)[0]
           ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'GITSScheduler' object has no attribute 'get_sigmas'

**Comment by JaneDoe84** [comment]
> In this file ..\ComfyUI\custom_nodes\comfyui-impact-pack\modules\impact\special_samplers.py
> change line 667 to:
> return scheduler.execute(coeff, steps, denoise)[0]

THANK YOU ! This worked, wonder why Dev say Comfyui fault...
